# Generated by Django 5.2.7 on 2025-11-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_game_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='trailer',
            field=models.TextField(null=True),
        ),
    ]
