# Generated by Django 5.2.7 on 2025-12-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_game_trailer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gameslist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.TextField(unique=True)),
                ('title', models.TextField()),
                ('games', models.ManyToManyField(blank=True, to='ui.game')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
